### ISSUE TITLE
php8.4.1，topthink/think-filesystem2.0.3，League\\Flysystem\\Filesystem::get(): Implicitly marking parameter $handler as nullable is deprecated, the explicit nullable type must be used instead

### ISSUE THREAD

**Issue by 2606062632** [top-think/think-filesystem#12]
League\\Flysystem\\Filesystem::get(): Implicitly marking parameter $handler as nullable is deprecated, the explicit nullable type must be used instead

**Comment by liu21st** [comment]
这个库不是我们的

**Comment by 2606062632** [comment]
> 这个库不是我们的

依赖的版本太低了吧："league/flysystem": "^1.1.4"，这个库已经更新到了3.16，是否需要更新下依赖的版本？

**Comment by augushong** [comment]
直接不要用扩展了，直接内置吧。
这个代码已经集成到flysystem3了。
tp有提供的extend机制，可以利用起来。
https://gitee.com/ulthon/ulthon_admin/tree/master/extend/think/filesystem

**Comment by liu21st** [comment]
> 直接不要用扩展了，直接内置吧。 这个代码已经集成到flysystem3了。 tp有提供的extend机制，可以利用起来。 https://gitee.com/ulthon/ulthon_admin/tree/master/extend/think/filesystem

之前内置的 但这个库经常出安全问题 所以才独立的

**Comment by augushong** [comment]
开发者愿意的自己内置就可以了。框架保持精简和灵活性，挺好的。

**Comment by 2606062632** [comment]
> > 直接不要用扩展了，直接内置吧。 这个代码已经集成到flysystem3了。 tp有提供的extend机制，可以利用起来。 https://gitee.com/ulthon/ulthon_admin/tree/master/extend/think/filesystem
> 
> 之前内置的 但这个库经常出安全问题 所以才独立的

我不愿意自己内置，麻烦调整一下吧，看看是更新到最新的league/flysystem依赖还是怎么修复一下

**Comment by augushong** [comment]
调整不了的，影响扩展依赖和php版本。
像这种情况，自己内置是最佳方案。因为自己内置也是完全符合tp的扩展性设计的。并不是说tp没提供这种扩展性，需要改造框架才行。

> > > 直接不要用扩展了，直接内置吧。 这个代码已经集成到flysystem3了。 tp有提供的extend机制，可以利用起来。 https://gitee.com/ulthon/ulthon_admin/tree/master/extend/think/filesystem
> > 
> > 
> > 之前内置的 但这个库经常出安全问题 所以才独立的
> 
> 我不愿意自己内置，麻烦调整一下吧，看看是更新到最新的league/flysystem依赖还是怎么修复一下

**Comment by 2606062632** [comment]
> 调整不了的，影响扩展依赖和php版本。 像这种情况，自己内置是最佳方案。因为自己内置也是完全符合tp的扩展性设计的。并不是说tp没提供这种扩展性，需要改造框架才行。
> 
> > > > 直接不要用扩展了，直接内置吧。 这个代码已经集成到flysystem3了。 tp有提供的extend机制，可以利用起来。 https://gitee.com/ulthon/ulthon_admin/tree/master/extend/think/filesystem
> > > 
> > > 
> > > 之前内置的 但这个库经常出安全问题 所以才独立的
> > 
> > 
> > 我不愿意自己内置，麻烦调整一下吧，看看是更新到最新的league/flysystem依赖还是怎么修复一下

你话咋

**Comment by augushong** [comment]
不过tp8可以考虑升级一下依赖了。
