### ISSUE TITLE
facade Filesystem 移植过来

### ISSUE THREAD

**Issue by yuanzhihai** [top-think/think-filesystem#2]
既然和框架分离了，就要彻底分离  面板(facade)中的 Filesystem 也应该移植过来
框架留着也没有用

**Comment by augushong** [comment]
不是，facade的filesystem要留着的，框架核心用到了。而且要不然这个次更新，生态就断裂了。

现在这样做，可以更灵活的定制think-filesystem的扩展。

**Comment by yuanzhihai** [comment]
> 不是，facade的filesystem要留着的，框架核心用到了。而且要不然这个次更新，生态就断裂了。
> 
> 现在这样做，可以更灵活的定制think-filesystem的扩展。

没明白你啥意思？和生态啥关系？

**Comment by tlerbao** [comment]
感觉就是你这个建议，搞得我接管整个 filesystem service，然后用默认门面不行了，靠。。

提出去干嘛呢？
