### ISSUE TITLE
think-filesystem 2.0版本中的think\filesystem\Driver类报错

### ISSUE THREAD

**Issue by HeroTianTYJ** [top-think/think-filesystem#5]
第58行代码return new Filesystem($adapter, count($config) > 0 ? $config : null);中的null应改为[]，因为League\Flysystem\Filesystem类的构造函数的第二个参数要求传递数组。
在php8.1中，如果传递null，上传文件时会报错。

**Comment by oyvfhp** [comment]
@yunwuxin  大家应该都有这个错误，官网不提供一下说明文档么？

**Comment by idcpj** [comment]
找到 src/filesystem/Driver.php 目录的 58 行
```
return new Filesystem($adapter, count($config) > 0 ? $config : null);
```
 改成
```
return new Filesystem($adapter, count($config) > 0 ? $config : []);
```

**Comment by oyvfhp** [comment]
`
return [
    'default' =>  'local',
    'disks'   => [
        'local'  => [
            'type' => 'local',
            'root'   => app()->getRuntimePath() . 'storage',
        ],
        'public' => [
            'type'     => 'local',
            'root'       => app()->getRootPath() . 'public/storage',
            'url'        => '/storage',
            'visibility' => 'public',
        ],
        // 更多的磁盘配置信息
    ],
];
`

官方已经更新文档了，配置一下url或visibility的参数即可，最好还是别改动源码，升级比较麻烦。
